### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by yamajiro** [yamajiro/sqlcrush#1]
- [x] Fix crush opening SQLite db
- [x] Fix crush updating non-primary key table 
- [x] Enable view and edit data contained CJK character
- [ ] 生SQLの実行からバインド実行に変更
- [ ] テーブルリストの順序を固定化
- [ ] カラムの変更・追加に対応
- [ ] 高速化
